projection method where data with m-columns (features) is projected into a subspace with m or fewer columns, whilst retaining the essence of the original data. <br>

PCA is an operation applied to a dataset, represented by an n × m matrix A that results in a projection of A which we will call B <br>

$$ A = \begin{pmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2} \\
\end{pmatrix}$$

<br>

$$ B = PCA(A) $$

first step is to calculate mean of column <br> 

$$ M = mean(A) $$

Next, center the values in each column by subtracting the mean column value.<br>
$$ C = A - M $$

The next step is to calculate the covariance matrix of the centered matrix C. Correlation is a normalized measure of the amount and direction (positive or negative) that two columns change together. Covariance is a generalized and unnormalized version of correlation across multiple columns. A covariance matrix is a calculation of covariance of a given matrix with covariance scores for every column with every other column, including itself.

<br> 

$$ V = cov(C) $$

finally caluclate the eigendecomposition of covariance matrix V

$$ values, vectors = eig(V) $$

The eigenvectors represent the directions or components for the reduced subspace of B,
whereas the eigenvalues represent the magnitudes for the directions. The eigenvectors can be
sorted by the eigenvalues in descending order to provide a ranking of the components or axes of
the new subspace for A. If all eigenvalues have a similar value, then we know that the existing
representation may already be reasonably compressed or dense and that the projection may
offer little. If there are eigenvalues close to zero, they represent components or axes of B that
may be discarded. A total of m or less components must be selected to comprise the chosen
subspace. Ideally, we would select k eigenvectors, called principal components, that have the k
largest eigenvalues <br>

$$ B = select(values,vectors) $$




Other matrix decomposition methods can be used such as Singular-Value Decomposition,
or SVD. As such, generally the values are referred to as singular values and the vectors of the
subspace are referred to as principal components. Once chosen, data can be projected into the
subspace via matrix multiplication. <br>
$$ P = B^T · A $$
Where A is the original data that we wish to project, BT
is the transpose of the chosen
principal components and P is the projection of A

In [3]:
import numpy as np
#  define matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# column means
M = np.mean(A.T, axis=1)
# center columns by subtracting column means
C = A - M
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
# factorize covariance matrix
values, vectors = np.linalg.eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)


[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [4]:
# using scikit-learn
import numpy as np
from sklearn.decomposition import PCA
# define matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# create the transform
pca = PCA(2)
# fit transform
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)


[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]
