# LU decomposition 
for square matrices and decomposes a matrix into L and U components.
\begin{gather*}
A=L.U
\end{gather*}
L is the lower triangular matrix. <br>
U is the upper triangular matrix.

The LU decomposition is found using an iterative numerical process and can fail for those
matrices that cannot be decomposed or decomposed easily. A variation of this decomposition
that is numerically more stable to solve in practice is called the LUP decomposition, or the LU
decomposition with partial pivoting
\begin{gather*}
A=P.L.U
\end{gather*}

The rows of the parent matrix are re-ordered to simplify the decomposition process and the
additional P matrix specifies a way to permute the result or return the result to the original
order. There are also other variations of the LU. The LU decomposition is often used to simplify
the solving of systems of linear equations, such as finding the coefficients in a linear regression,
as well as in calculating the determinant and inverse of a matrix

In [5]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]])

print(A)
#decompose 
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)


[[ 2 -1 -2]
 [-4  6  3]
 [-4 -2  8]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[ 1.    0.    0.  ]
 [ 1.    1.    0.  ]
 [-0.5  -0.25  1.  ]]
[[-4.    6.    3.  ]
 [ 0.   -8.    5.  ]
 [ 0.    0.    0.75]]
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]


python implementation of LU decomposition using doolittle algorithm <br>
Terms of U matrix are given by:


$$ i>0 \Rightarrow u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik} $$
To ensure that the algorithm is numerically stable when , a pivoting matrix P is used to re-order so that the largest element of each column of A gets shifted to the diagonal of A <br>

Terms of L matrix are given by:

$$ j>0 \Rightarrow l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik})  $$

In [8]:
MAX = 100
 
def pivot_matrix(M):
    """Returns the pivoting matrix for M, used in Doolittle's method."""
    m = len(M)

    # Create an identity matrix, with floating point values                                                                                                                                                                                            
    id_mat = [[float(i ==j) for i in range(m)] for j in range(m)]

    # Rearrange the identity matrix such that the largest element of                                                                                                                                                                                   
    # each column of M is placed on the diagonal of of M                                                                                                                                                                                               
    for j in range(m):
        row = max(range(j, m), key=lambda i: abs(M[i][j]))
        if j != row:
            # Swap the rows                                                                                                                                                                                                                            
            id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

    return id_mat

def lu_decomposition(A):
    """Performs an LU Decomposition of A (which must be square)                                                                                                                                                                                        
    into PA = LU. The function returns P, L and U."""
    n = len(A)

    # Create zero matrices for L and U                                                                                                                                                                                                                 
    L = np.zeros((n,n))
    U = np.zeros((n,n))

    # Create the pivot matrix P and the multipled matrix PA                                                                                                                                                                                            
    P = pivot_matrix(A)
    PA = np.dot(P, A)

    # Perform the LU Decomposition                                                                                                                                                                                                                     
    for j in range(n):
        # All diagonal entries of L are set to unity                                                                                                                                                                                                   
        L[j][j] = 1.0

        # LaTeX: u_{ij} = a_{ij} - \sum_{k=1}^{i-1} u_{kj} l_{ik}                                                                                                                                                                                      
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = PA[i][j] - s1

        # LaTeX: l_{ij} = \frac{1}{u_{jj}} (a_{ij} - \sum_{k=1}^{j-1} u_{kj} l_{ik} )                                                                                                                                                                  
        for i in range(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (PA[i][j] - s2) / U[j][j]

    return (P, L, U)
 
mat = [[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]]
print("parent matrix")
print(np.array(mat))

# print("pivot matrix")
# P = np.array([[ 0., 1., 0.],
# [ 0., 0., 1.],
# [ 1., 0., 0.]])
P,L,U =lu_decomposition(mat)

A = np.dot(P,np.dot(L,U))
print(A)

parent matrix
[[ 2 -1 -2]
 [-4  6  3]
 [-4 -2  8]]
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]


# QR decomposition 
QR decomposition is done on M x N matrices (not limited to square matrices) <br>

$$ A = Q . R $$

the QR decomposition is often used to solve systems of linear equations, although is not limited to square matrices <br>


In [1]:
#  QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)


[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Cholesky Decomposition 

The Cholesky decomposition is for square symmetric matrices where all eigenvalues are greater than zero, so-called positive definite matrices.<br>
$$ A = L.L^T $$

L is the lower triangular matrix and $ L^T $
is the transpose of L. <br>

The decompose can also be written as the product of the upper triangular matrix, for example:
$$ A = U^T.U $$
Where U is the upper triangular matrix. The Cholesky decomposition is used for solving linear least squares for linear regression, as well as simulation and optimization methods. <br> 
When decomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the LU decomposition and should be preferred in these cases

In [2]:
#  Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


python implementation of cholesky <br>

$$ l_{kk} = \sqrt {a_{kk} - \sum\limits _{k-1}^{j=1}{l^2_{kj}} }  $$ 
$$ l_{ik} = \frac{1}{l_{kk}} (a_{ik} - \sum\limits _{k-1}^{j=1}{l_{ij}l_{kj}}), i>k $$



In [3]:

from math import sqrt
from pprint import pprint

def cholesky(A):
    """Performs a Cholesky decomposition of A, which must 
    be a symmetric and positive definite matrix. The function
    returns the lower variant triangular matrix, L."""
    n = len(A)

    # Create zero matrix for L
    L = [[0.0] * n for i in range(n)]

    # Perform the Cholesky decomposition
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): # Diagonal elements
                # LaTeX: l_{kk} = \sqrt{ a_{kk} - \sum^{k-1}_{j=1} l^2_{kj}}
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                # LaTeX: l_{ik} = \frac{1}{l_{kk}} \left( a_{ik} - \sum^{k-1}_{j=1} l_{ij} l_{kj} \right)
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L
 
A = [[2, 1, 1],
[1, 2, 1],
[1, 1, 2]]
L = cholesky(A)

print ("A:")
pprint(A)

print ("L:")
pprint(L)

A:
[[2, 1, 1], [1, 2, 1], [1, 1, 2]]
L:
[[1.4142135623730951, 0.0, 0.0],
 [0.7071067811865475, 1.224744871391589, 0.0],
 [0.7071067811865475, 0.4082482904638632, 1.1547005383792515]]
