Perhaps the most used type of matrix decomposition is the eigendecomposition that decomposes a matrix into eigenvectors and eigenvalues. This decomposition also plays a role in methods used in machine learning, such as in the Principal Component Analysis method or PCA

A vector is an eigenvector of a matrix if it satisfies the following equation. <br>
$$ A.v = \lambda .v $$
This is called the eigenvalue equation, where A is the parent square matrix that we are decomposing, v is the eigenvector of the matrix, and λ is the lowercase Greek letter $\lambda$ and represents the eigenvalue scalar <br>

The parent matrix can be shown to be a product of the eigenvectors and eigenvalues <br>

$$ A = Q.\Lambda.Q^-1 $$

Where Q is a matrix comprised of the eigenvectors, $\Lambda$ is the uppercase Greek letter lambda and is the diagonal matrix comprised of the eigenvalues, and $Q^-1$ is the inverse of the matrix comprised of the eigenvectors. <br>

eigendecompostion can be used to calculate the principal components of amtrix in PCA method .i.e reduce the dimensionality of data.

In [1]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

values, vectors = np.linalg.eig(A)

print(values) # list of eigen values 
print(vectors) # column list of eigenvectors

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [2]:
#  define matrix
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# factorize
values, vectors = np.linalg.eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0]) # B = A.v1
print(B)
C = vectors[:, 0] * values[0] # C =  lambda_1 . v1
print(C)


[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [4]:
# define matrix
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = np.linalg.eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
Q_inverse = np.linalg.inv(Q)
# create diagonal matrix from eigenvalues
lambd =np.diag(values)
# reconstruct the original matrix
B = Q.dot(lambd).dot(Q_inverse)

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
