The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.
$$ A = U. \sum . V^T $$
A is the real m × n matrix that we wish to decompose, U is an m × m matrix, $\sum$ represented by the uppercase Greek letter sigma) is an m × n diagonal matrix, and $V
^T$ is the V transpose of an n × n matrix where T is a superscript.


The diagonal values in $\sum$ matrix are called singular values of the original matrix A. <br>
The columns of U matrix are called left-singular vectors of A, and the columns of V are called right-singular vectors of A.

In [19]:
import numpy as np

#  define a matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, VT = np.linalg.svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Reconstruct matrix <br>

The original matrix can be reconstructed from the U, Σ, and $V^T$ elements. The U, s, and V elements returned from the svd() cannot be multiplied directly. The s vector must be converted into a diagonal matrix using the diag() function <br>

After creating the square Σ diagonal matrix, the sizes of the matrices are relative to the original m × n matrix that we are decomposing, as follows:
$$ U(m × m) · Σ(n × n) · V^T(n × n)  $$


Where, in fact, we require:
$$U(m × m) · Σ(m × n) · V^T(n × n) $$

We can achieve this by creating a new Σ matrix of all zero values that is m × n (e.g. more
rows) and populate the first n × n part of the matrix with the square diagonal matrix calculated
via diag().

In [20]:
 # define matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, VT = np.linalg.svd(A)
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1])) # (mxn)
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Pseudoinverse 

Matrix inversion is not defined for matrices that are not square. [...] When A has more columns than rows, then solving a linear equation using the pseudoinverse provides one of the many possible solutions. <br>

The pesudoinverse is denoted as $A^+$ <br>

$$ A^+ = V.D^+.U^T $$ 

$D^+$ is the pseudoinverse of diagonal matrix $\sum$ and $U^T$. <br>

U and V are from the SVD operation.
$$ A = U.\sum.V^T$$ 
The $D^+$ can be calculate by creating a diagonal matrix from Σ, calculating the reciprocal of each non-zero element in Σ, and taking the transpose if the original matrix was rectangular <br>

$$
\sum = \begin{pmatrix}
s_{1,1} & 0 & 0\\
0 & s_{2,2} & 0\\
0 & 0 & s_{3,3}\\
\end{pmatrix}$$

$$ D^+ = \begin{pmatrix}
\frac{1}{s_{1,1}} & 0 & 0\\
0 & \frac{1}{s_{2,2}} & 0\\
0 & 0 & \frac{1}{s_{3,3}}\\
\end{pmatrix}$$ 

In [21]:
# define matrix
A = np.array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)
# calculate pseudoinverse
B = np.linalg.pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.28757642e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [22]:
A = np.array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
U, s, VT = np.linalg.svd(A)
d = 1.0/s
print(d)
D_pinv = np.zeros((A.shape[1],A.shape[0]))
D_pinv[:A.shape[1],:A.shape[1]] = np.diag(d)
print(D_pinv)
A_pinv = VT.T.dot(D_pinv).dot(U.T)

print(A_pinv)

[ 0.70081527 15.95333376]
[[ 0.70081527  0.          0.          0.        ]
 [ 0.         15.95333376  0.          0.        ]]
[[-1.00000000e+01 -5.00000000e+00  1.28565458e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


# Dimensionality reduction

Data with a large number of features, such as more features (columns) than observations (rows) may be reduced to a smaller subset of features that are most relevant to the prediction problem. The result is a matrix with a lower rank that is said to approximate the original matrix. To do this we can perform an SVD
operation on the original data and select the top k largest singular values in Σ. These columns can be selected from Σ and the rows selected from $V^T$


$$ B = U. \Sigma_{k} . V_{k}^T $$ 

An Approx B of the original vector A can be reconstructed. <br>
Tn practice, we can retain and work with a descriptive subset of the data called T. <br>
This is a dense summary of the matrix or a projection.
$$ T = U · Σ_{k} $$
Further, this transform can be calculated and applied to the original matrix A as well as
other similar matrices.
$$ T = A · V_{k} $$


In [23]:
#  define matrix
A = np.array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# factorize
U, s, VT = np.linalg.svd(A)
# create m x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(VT))
print(B)
T = U.dot(Sigma)
print(T)
T = A.dot(VT.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


scikit-learn provides a TruncatedSVD class that implements this capability directly. The TruncatedSVD class can be created in which you must specify the number of desirable features or components to select, e.g. 2. Once created, you can fit the transform (e.g. calculate $V^T_{k}$) by calling the fit() function, then apply it to the original matrix by calling the transform() function. The result is the transform of A called T above. The example below demonstrates the TruncatedSVD class.


In [24]:
from sklearn.decomposition import TruncatedSVD
# define matrix
A = np.array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
